pipeline:
  build:
    image: spritsail/docker-build
    repo: mono-dev
    build_args:
      - MONO_PACKAGE=${PACKAGE}
      - MONO_DESC=${DESC}

  test:
    image: mono-dev
    commands:
      - mono --version
      - apk add ca-certificates-mono
      - update-ca-certificates

  publish:
    image: spritsail/docker-publish
    when: { branch: [ master ], event: [ push, tag, deployment ] }
    secrets: [ docker_username, docker_password ]
    from: mono-dev
    repo: spritsail/mono
    tags: ${TAG}

matrix:
  include:
    - TAG: runtime
      DESC: "Mono runtime without any reference assemblies"
      PACKAGE:
    - TAG: 3.5
      DESC: "Mono runtime, including the 2.0 and 3.5 reference assemblies"
      PACKAGE: mono-reference-assemblies-3.5
    - TAG: 4.5,latest
      DESC: "Mono runtime, including the default 4.5 reference assemblies"
      PACKAGE: mono-reference-assemblies
    - TAG: 4.x
      DESC: "Mono runtime, including the 4.5 and 4.x reference assemblies"
      PACKAGE: mono-reference-assemblies-4.x
